### ISSUE TITLE
Restore borders

### ISSUE THREAD

**Issue by vrde** [vrde/i3-quiet#3]
*Reported [on reddit](https://www.reddit.com/r/i3wm/comments/eqzq1d/need_to_focus_try_i3quiet_mode/ff26wwt/).*

# Problem

When exiting quiet mode, in some cases borders are not restored to their original state.

# Solution

If there is a *border toggle* command, use it. Otherwise some more complex logic to store the previous state of the window has to be implemented.

**Comment by tcaxle** [comment]
`# i3-msg border toggle` Will toggle between states `none`, `1pixel`, and `normal`. However, if the user has `none` as their default borders (like me) this will turn on the borders when returning from quiet mode.

I suggest adding variables to the start of `quiet.py`:
```
#!/usr/bin/env python

# Choose borders from '1pixel' 'normal' 'none' 'pixel X'
DEFAULT_BORDERS = "1pixel"
ZEN_BORDERS = "none"

...

def enable_zen_mode(...):
    ...
    'border {}'.format(ZEN_BORDERS)
    ....

def disable_zen_mode(...):
    ...
    'border {}'.format(DEFAULT_BORDERS)
    ...

...
```
Then point users to these variables in the README.md

**Comment by vdg0** [comment]
Hi, i report the issue in reddit: https://www.reddit.com/r/i3wm/comments/eqzq1d/need_to_focus_try_i3quiet_mode/ff26wwt
Maybe we can use https://i3ipc-python.readthedocs.io/en/latest/con.html#i3ipc.Con
to try to get the previous state of border and set that when exit the quiet-mode. 

Maybe there is a good example to review at https://github.com/altdesktop/i3ipc-python/tree/master/examples

o/

**Comment by vrde** [comment]
Fixed by storing the current border value, see:

https://github.com/vrde/i3-quiet/blob/5bf07202c7b38f6ea71dcca8229f18e81bad0741/quiet-cmd.py#L41

And:

https://github.com/vrde/i3-quiet/blob/5bf07202c7b38f6ea71dcca8229f18e81bad0741/quiet-cmd.py#L55-L59
